### ISSUE TITLE
context.params.slug is not an array if U provide top level route

### ISSUE THREAD

**Issue by tomaszrondio** [toomuchdesign/next-page-tester#110]
## 🐛 Bug Report
```
const { render } = await getPage({
      route: "/somerandomurl",
    });
```
results in context.params.slug being a string "somerandomurl" but if U use "/some/thing" as a route it will be an array

## Expected behavior

Slug should be an array even if there is only one element

**Comment by toomuchdesign** [comment]
Hi @tomaszrondio!
What's the pathname of the relevant page file?

**Comment by tomaszrondio** [comment]
I have `[...slug].jsx` that catches pretty much all routes.

**Comment by toomuchdesign** [comment]
Found the issue. Current implementation has some intrinsic limitations which requires a bit of time and refactoring. I'll try to work on it this weekend.
