### ISSUE TITLE
Cannot find module 'cookie'

### ISSUE THREAD

**Issue by jansepke** [toomuchdesign/next-page-tester#111]
## 🐛 Bug Report

I think with version 0.15.0 a dependency to the `cookie` package was introduced in `makeContextObject.ts` but not added as dependency to `package.json`.

## To Reproduce

directly happens on executing `initTestHelpers()`

## Expected behavior

`cookie` added as dependency.

## Run `npx envinfo --preset jest`

```bash
  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  npmPackages:
    jest: 26.6.3 => 26.6.3 
```
Next.js version: 10.0.5

**Comment by Meemaw** [comment]
Yeah, forgot to add `cookie` to dependencies, was somehow thinking it is a dependency of `nextjs`. Should be fixed in https://github.com/toomuchdesign/next-page-tester/pull/112
