### ISSUE TITLE
render() error: ReferenceError: document is not defined

### ISSUE THREAD

**Issue by paoli-a** [toomuchdesign/next-page-tester#118]
## 🐛 Bug Report

When a Material UI component is added somewhere on the rendered page, an error occurs with this text:
```
The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/en/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.
    
    ReferenceError: document is not defined

       7 |         route: "/",
       8 |     });
    >  9 |     render();
         |     ^
      10 |     expect(
      11 |       screen.getByRole("heading", { name: "Welcome to Next.js!" })
      12 |     ).toBeInTheDocument();

      at createStyle (node_modules/jss/dist/jss.cjs.js:1773:12)
      at new DomRenderer (node_modules/jss/dist/jss.cjs.js:1805:31)
      at new StyleSheet (node_modules/jss/dist/jss.cjs.js:1056:23)
      at Jss.createStyleSheet (node_modules/jss/dist/jss.cjs.js:2059:17)
      at attach (node_modules/@material-ui/styles/makeStyles/makeStyles.js:116:39)
      at node_modules/@material-ui/styles/makeStyles/makeStyles.js:258:7
      at useSynchronousEffect (node_modules/@material-ui/styles/makeStyles/makeStyles.js:211:14)
      at useStyles (node_modules/@material-ui/styles/makeStyles/makeStyles.js:250:5)
      at Object.WithStyles(ForwardRef(Button)) [as render] (node_modules/@material-ui/styles/withStyles/withStyles.js:73:21)
      at ReactDOMServerRenderer.render (node_modules/react-dom/cjs/react-dom-server.node.development.js:3872:44)
      at ReactDOMServerRenderer.read (node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
      at Object.renderToString (node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
      at node_modules/next-page-tester/dist/makeRenderMethods.js:13:75
      at Object.executeAsIfOnServerSync (node_modules/next-page-tester/dist/server.js:42:16)
      at serverRenderToString (node_modules/next-page-tester/dist/makeRenderMethods.js:13:28)
      at serverRender (node_modules/next-page-tester/dist/makeRenderMethods.js:18:26)
      at render (node_modules/next-page-tester/dist/makeRenderMethods.js:37:30)
      at Object.<anonymous> (tests/index.test.js:9:5)
```

## To Reproduce

- create Next.js app and install dependencies:

```bash
npx create-next-app
# inside the app directory
yarn add --dev jest @testing-library/jest-dom @testing-library/react @testing-library/dom babel-jest identity-obj-proxy
yarn add --dev next-page-tester
yarn add @material-ui/core
```
- add `.babelrc`, `jest.config.js`, `setupTests.js` and `tests/index.test.js` as in the demo project linked below.
- add a material ui component in the `index.js` page (e.g: `<Button color="primary">Hello World</Button>`).

The test passes without the button but returns the above error when adding it. 

## Expected behavior

The test should pass with or without the material ui component.

## Link to repl or repo

[Here is a minimal reproduction](https://github.com/paoli-a/next-page-tester-material-ui)
You can run the test with `yarn test`.

## Run `npx envinfo --preset jest`

```bash
System:
    OS: Linux 4.10 Linux Mint 18.3 (Sylvia)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 14.15.3 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.14.9 - /usr/local/bin/npm
  npmPackages:
    jest: ^26.6.3 => 26.6.3 
```

**Comment by toomuchdesign** [comment]
Hi @paoli-a,
thanks for providing the runnable example, very appreciated.

In order to fix the error you should manually patch `jest-runner` as explained here:
https://github.com/toomuchdesign/next-page-tester#optional-patch-jest

It's a necessary step for advanced use cases as yours, as long as Jest v27 gets released.

**Comment by paoli-a** [comment]
Thanks a lot! It solves my issue.

**Comment by jasonwilliams** [comment]
im getting ` TypeError: Cannot read property 'body' of undefined` on https://github.com/jasonwilliams/nextjs9-typescript-server-vscode-example i'm assuming its the same problem?

```
 Blog page › renders blog page

    TypeError: Cannot read property 'body' of undefined

       8 |     });
       9 | 
    > 10 |     render();
         |     ^
      11 | 
      12 |     // expect(screen.getByText("Blog")).toBeInTheDocument();
      13 | 

      at serverRender (node_modules/next-page-tester/dist/makeRenderMethods.js:22:39)
      at render (node_modules/next-page-tester/dist/makeRenderMethods.js:39:30)
      at Object.<anonymous> (tests/pages/items.test.tsx:10:5)
```

**Comment by jasonwilliams** [comment]
I've managed to get round this by using `@testing-library/react`'s render instead of the one returned by `getPage`. I don't know if that's correct but it works

**Comment by Meemaw** [comment]
That will work because it skips the server side rendering. It however doesn't 100% match the behaviour in nextjs.

**Comment by toomuchdesign** [comment]
@jasonwilliams Are you encountering the described error with or without the aforementioned Jest patch?

**Comment by jasonwilliams** [comment]
Without the patch

**Comment by frontendtony** [comment]
> Hi @paoli-a,
> thanks for providing the runnable example, very appreciated.
> 
> In order to fix the error you should manually patch `jest-runner` as explained here:
> https://github.com/toomuchdesign/next-page-tester#optional-patch-jest
> 
> It's a necessary step for advanced use cases as yours, as long as Jest v27 gets released.

@toomuchdesign the link to the fix here no longer exists. I'm facing the same issue at the moment. Side note: I had to downgrade jest to 26* due to a separate issue which you're currently looking into, so upgrading jest won't work for me

**Comment by frontendtony** [comment]
Never mind. Found it after a little digging. My tests are running fine now

https://github.com/toomuchdesign/next-page-tester/blob/82c61105e38d85c5b8c92dbcf13500e941d9d7b7/README.md#optional-patch-jest

**Comment by fernando-f** [comment]
I had the same problem. It was because I had a local library that I was using, which was liked with yarn link. Removing with `yarn unlink @libray-name` and `yarn install --force` did the trick.

**Comment by fernandodof** [comment]
I had the same problem. It was because I had a local library that I was using, which was liked with yarn link. Removing with `yarn unlink @libray-name` and `yarn install --force` did the trick.
