### ISSUE TITLE
next config set by jest tests doing setConfig isn't read by next-page-tester

### ISSUE THREAD

**Issue by DavidOrchard** [toomuchdesign/next-page-tester#129]
## 🐛 Bug Report

v0.17.0 introduced the ability to read from the next config.  However, the next config can be set during jest tests, so it is separate from the next config. It is set via our code in jestSetup.ts:

```
import { setConfig } from "next/config";
setConfig({
  publicRuntimeConfig: {
...
```
which calls next's
```
    envConfig.setConfig({
      serverRuntimeConfig,
      publicRuntimeConfig,
    })
```
which calls runTimeConfig.ts
```
export function setConfig(configValue: any): void {
  runtimeConfig = configValue
}

```

The next-page-tester should do something like read in runtimeConfig via the runTimeConfig.ts
```
export default () => {
  return runtimeConfig
}
```

as default and then override with next config if the runtimeConfig is undefined.

## To Reproduce

Set the runtimeConfig dynamically in jest setup.
run a jest test that uses runtimeConfig

## Expected behavior

The jestSetup calls to setConfig take precedence of next's file config.

## Run `npx envinfo --preset jest`

Paste the results here:

```bash
  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 12.16.0 - ~/.nvm/versions/node/v12.16.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.0/bin/npm
  npmPackages:
    jest: ^26.6.3 => 26.6.3 
```

**Comment by toomuchdesign** [comment]
Hi @DavidOrchard,
we definitely didn't consider the option of manually calling `next/config`'s `setConfig` manually. It's not even mentioned in [Next.js docs](https://nextjs.org/docs/api-reference/next.config.js/runtime-configuration). :)

Do you know whether it's considered good practice? I thought `setConfig` as a private method called internally by Next.js (in fact `next-page-tester` also uses it to set runtime config from next.config.js).

Is there any use case not covered by setting runtime config from `next.config.js`?

**Comment by jgan42** [comment]
> Hi @DavidOrchard, we definitely didn't consider the option of manually calling `next/config`'s `setConfig`. It's not even mentioned in [Next.js docs](https://nextjs.org/docs/api-reference/next.config.js/runtime-configuration). :)
> 
> Do you know whether it's considered good practice? I thought `setConfig` as a private method called internally by Next.js (in fact `next-page-tester` also uses it to set runtime config from next.config.js).
> 
> Is there any use case not covered by setting runtime config from `next.config.js`?

If it's not meant to be used I don't understand why it is exposed. At the very least it should be mentioned as a comment in the code or something =/
