### ISSUE TITLE
getPage seems to fail on the second run

### ISSUE THREAD

**Issue by jasonwilliams** [toomuchdesign/next-page-tester#144]
## 🐛 Bug Report

When i run one test with getPage() it works fine, but if i duplicate that test and run it again inside another `it()` i get an error.

Im trying to write multiple tests to test different state/data being sent but i can only use one `getPage` per test-suite
```
    TypeError: Cannot destructure property 'getInitialProps' of 'AppComponent' as it is undefined.

      at Object.fetchAppData (node_modules/next-page-tester/dist/_app/fetchAppData.js:12:13)
      at Object.fetchRouteData (node_modules/next-page-tester/dist/fetchData/fetchRouteData.js:9:42)
      at Object.getPageInfo (node_modules/next-page-tester/dist/makePageElement.js:24:40)
      at getPage (node_modules/next-page-tester/dist/getPage.js:84:38)
```

**Comment by jasonwilliams** [comment]
> PS. Are you calling something like jest.resetModules() between tests?

No im not calling that, there's nothing being called between tests (not explicitly by me anyway)

Yeah im trying to see if i can isolate it.
Manually setting nextRoot doesn't help either

**Comment by jasonwilliams** [comment]
In getAppFile.js it seems to return an object pointing to undefined values.
I've checked the absolute path to the _app.tsx and it's correct. But for some reason require([path]) returns `{default: undefined}`

![image](https://user-images.githubusercontent.com/936006/107352374-aa1b1280-6ac3-11eb-8a25-eac0038d7e1f.png)

**Comment by Meemaw** [comment]
This happens when import fails. It can for example mean that you have an error at module initialisation time or a cyclic import somewhere.

The DX from our side is not ideal and should probably be improved. We should throw an error indicating that import failed even though the file exists. I've been hit by this before. cc @toomuchdesign

**Comment by jasonwilliams** [comment]
Yep, https://github.com/toomuchdesign/next-page-tester/blob/master/src/loadPage.ts#L15 is throwing because my `_app.tsx` tries to import a `.css` file. Looks like its not ignoring it for some reason.

Maybe i need to look into my babel configuration?

**Comment by jasonwilliams** [comment]
Yep that fixed it!
I just needed to sort my statc assets out.

Sadly this framework swallowed the error just like you said @Meemaw 
The fix should be to have a separate try to the [requires()](https://github.com/toomuchdesign/next-page-tester/blob/master/src/loadPage.ts#L15-L16) and log out if they fail, then the user has the information to fix it

**Comment by toomuchdesign** [comment]
Hi @jasonwilliams, hi @Meemaw!
do you have any guess about how/where we're swallowing errors? If so, I'd love to set this information in the form of a failing test so that we can better consider improvements in this sense.

**Comment by Meemaw** [comment]
@toomuchdesign We're not swallowing any errors per se. Unfortunately `require` mechanism is a bit flawed and worn throw an error if the import failed. It will just resolve to `undefined`.

We can easily detect that case if the file exists but the `require` resolved to `undefined`. In that we should throw an error with some useful information when this might happen:
- cyclic dependncies
- module initialization errors
- ...

**Comment by toomuchdesign** [comment]
I'm also noticing errors when `_app` imports external `.tsx` files.
I guess this might be caused to the fact that we use `require`. Is it somehow related to this is issue?

**Comment by Meemaw** [comment]
I think this happens due to some Typescript errors. Unfortunately you wont see those because `tsconfig.json` does not include test files. Perhaps this can be improved. If test files were removed to avoid compiling them in `build`, this is usually handled with a `tsconfig.build.json` which ignores them, but the default `tsconfig.json` should include them (this way errors will show in VSCode as well)

**Comment by toomuchdesign** [comment]
Yep @Meemaw, this was actually my issue! 👏 👏👏
