### ISSUE TITLE
Support client side navigation

### ISSUE THREAD

**Issue by Meemaw** [toomuchdesign/next-page-tester#15]
## 🚀 Feature Proposal

Support client side page navigation, e.g. `Link` and programatic navigation using router. This would make this library extremely useful for integration testing of NextJS applications.

Since this library is mocking the router, it is in full control over that and has access to handlers, right? In that case I assume this should be possible.

## Example

```js
describe('Blog page', () => {
  it('renders blog page', async () => {
    const Page = await getPage({
      route: '/blog/1',
    });

    render(Page);
    userEvent.click(screen.getByText('Link'))

    await screen.findByText('Linked page')
  });
});
```

**Comment by toomuchdesign** [comment]
Hi @Meemaw,
It could be actually feasible with a few changes in the way we currently render pages. I'll give it a try.

In the meanwhile feel free to provide further feedbacks in you have any.

**Comment by toomuchdesign** [comment]
Updates: PR #17, provides an initial implementation for this feature. `router.push` and `router.replace` currently supported.

@Meemaw, glad if you could take a look at it.

**Comment by Meemaw** [comment]
Great work @toomuchdesign 👍 I will test it locally on a real world application this weekend.

**Comment by toomuchdesign** [comment]
Shipped with v0.7.0.

**Comment by Meemaw** [comment]
@toomuchdesign I've quickly tested it today and the client side navigation works as expected! 🚀 

I've opened 2 additional feature requests that I think would be a great addition to the library. Let me know what you think or if you need help with any of it (perhaps I can help).

**Comment by toomuchdesign** [comment]
Sounds great @Meemaw!
