### ISSUE TITLE
env vars aren't available within next.config.js

### ISSUE THREAD

**Issue by jesstelford** [toomuchdesign/next-page-tester#151]
## 🐛 Bug Report

Next.js will load env vars before processing `next.config.js`, allowing access of `process.env.WHATEVER` to inform config values. `next-page-tester` does not load env vars until _after_ `next.config.js` is processed, resulting in `process.env.WHATEVER` always being `undefined`.

## To Reproduce

Create a `.env.local` with:

```
DOMAIN=https://example.com
```

Create a `next.config.js` with:

```javascript
module.exports = {
  i18n: {
    locales: ['en-AU'],
    defaultLocale: 'en-AU',
    domains: [
      {
        domain: process.env.DOMAIN,
        defaultLocale: 'en-AU',
      },
    ],
  },
}
```

Then run any test. Note Next throws an error:

```
    Invalid i18n.domains values:
    {"defaultLocale":"en-AU"}

    domains value must follow format { domain: 'example.fr', defaultLocale: 'fr', locales: ['fr'] }.
    See more info here: https://err.sh/next.js/invalid-i18n-config
```

The object is missing the `"domain"` key (because `process.env.DOMAIN` is `undefined`)

## Expected behavior

The env vars should be loaded before loading the config, and subsequently Next.js should not throw an error here.

## Link to repl or repo

Minimal reproduction: https://github.com/jesstelford/next-page-tester-bug-151

## Run `npx envinfo --preset jest`

Paste the results here:

```bash
  System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
  Binaries:
    Node: 12.20.1 - ~/.nvm/versions/node/v12.20.1/bin/node
    Yarn: 1.19.1 - ~/.config/yarn/global/node_modules/.bin/yarn
    npm: 6.14.9 - ~/dev/test/node_modules/.bin/npm
  npmPackages:
    jest: ^26.6.3 => 26.6.3
```

**Comment by Meemaw** [comment]
@jesstelford thanks for reporting this. Its indeed a bug in how we handle env/config variables.

I've prepared a [fix](https://github.com/toomuchdesign/next-page-tester/pull/152) that should solve your issues.
