### ISSUE TITLE
Catch all route 

### ISSUE THREAD

**Issue by icyJoseph** [toomuchdesign/next-page-tester#153]
## 🐛 Bug Report

When there's a page `/[...all].tsx` trying to `getPage` on `/sub/[route].tsx` has unwanted results, because `[...all].tsx` is selected on this heuristic, from getPageObject/getRouteInfo.js

```
  const matchingRouteInfo = pagePaths
        .map((pagePath, index) => {
        const result = pathname.match(pagePathRegexes[index]);
        if (result) {
            return makeRouteInfo_1.makeRouteInfo({
                route,
                pagePath,
                routeRegexCaptureGroups: result.groups,
            });
        }
    })
        .filter((result) => Boolean(result))
        .sort((a, b) => a.paramsNumber - b.paramsNumber);
    // Return the result with less page params
    return matchingRouteInfo[0];
```

Because `paramsNumber` for both routes equals 1. The ordering I believe comes from `fastGlob`, which returns `[.` above all else,  see `getPageObject/getPagePaths.js`, a quick check through their package documentation doesn't seem to offer a way to rank paths by specificity.

## To Reproduce

- On a next js project, create `pages/[...all].tsx` and `pages/sub/[route].tsx`. 

- Try to `renderPage` with route on `/sub/route0`.

- `[...all].tsx` is rendered.

## Expected behavior

Catch all routes should have less preference.

**Comment by osadi** [comment]
I've created a small reproduction repo here: https://github.com/osadi/next-page-tester
