### ISSUE TITLE
next/head tags are not populated on server or client render

### ISSUE THREAD

**Issue by jesstelford** [toomuchdesign/next-page-tester#154]
## 🐛 Bug Report

Using Next.js' `next/head` component fails to inject tags into the `<head>` of a document when rendered within next-page-tester.

My motivation here is to test that meta tags and other SEO-related items (LDJSON, microformat, etc), are being rendered to the `<head>` correctly, but to do so I need to be able to see what's in the head.

## To Reproduce

Try rendering anything using `next/head`:

```javascript
import React from "react";
import Head from "next/head";

const Home = () => {
  return (
    <Fragment>
      <Head>
        <title>Server Side Title</title>
      </Head>
      <h1>Hello world</h1>
    </Fragment>
  );
};

export default Home;
```

Then check the output within a test:

```javascript
const { serverRender } = await getPage({
  route: "/",
});

serverRender();

const serverHtml = document.documentElement.outerHTML;
// <html data-reactroot=\\"\\"><head></head><body><div id=\\"__next\\"><h1>Hello world</h1></div></body></html>
```

Note while a `<head>` tag does exist, the expected `<title>Server Side Title</title>` does not.

## Expected behavior

`next-page-tester` should correctly populate the `<head>` with `next/head` rendered items.

## Link to repl or repo

Minimal reproduction: https://github.com/jesstelford/next-page-tester-bug-154

## Run `npx envinfo --preset jest`

Paste the results here:

```bash
  System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
  Binaries:
    Node: 12.20.1 - ~/.nvm/versions/node/v12.20.1/bin/node
    Yarn: 1.19.1 - ~/.config/yarn/global/node_modules/.bin/yarn
    npm: 6.14.9 - ~/dev/test/node_modules/.bin/npm
  npmPackages:
    jest: ^26.6.3 => 26.6.3
```

**Comment by jesstelford** [comment]
I tried to do some debugging, but didn't get far.

I expected `updateHead` to be called here: https://github.com/toomuchdesign/next-page-tester/blob/0db34fe92de00df5e6cc40918470dfe53bbff68d/src/_document/render.tsx#L95-L102, but it never seems to be executed (the wrapping `renderPage` definitely is).

My suspicion is the instance of `HeadManagerContext` used here is _different_ to the one used by Next.js internally, which I think has a default `renderPage` method, so `next-page-tester` never gets to see the head state changes.

This has implications for the `useDocument: false` case earlier in `src/_document/render.tsx` due to it incorrectly short circuiting with an empty `<head>`.

**Comment by Meemaw** [comment]
Hi @jesstelford

Does it work correctly if you use `useDocument: true` (default is false). In that case it is probably indeed due to some short circuiting in our code.

**Comment by jesstelford** [comment]
The bug exists with both `useDocument: false` & `useDocument: true` unfortunately

**Comment by Meemaw** [comment]
Hey @jesstelford 👋 

If `useDocument=false` this is currently expected behaviour.

If ` useDocument=true` it should work for you. I've tried your reproducer in our repo and it correctly renders next/head tags. You might need to patch `jest` as described here: https://github.com/toomuchdesign/next-page-tester#optional-patch-jest

**Comment by jesstelford** [comment]
Ah-hah! Patching Jest worked to get the tests to include the `<head>` tag 🎉 

I did, however, notice a further issue: The client-side render doesn't appear to wait for `useEffect()`/`setState()` calls to complete, so any client-side `<Head>` renders aren't included in the output.

I've updated the reproduction repo with new instructions & code if you want to have a look: https://github.com/jesstelford/next-page-tester-bug-154

**Comment by Meemaw** [comment]
@jesstelford Could you open a separate issue for that? From quick look I think client side updates to `<Head>` do not work, so a simple reproducer would be a button that somehow toggles the `title` element on client side click.
