### ISSUE TITLE
useRouter doesn't return locale, locales, defaultLocale

### ISSUE THREAD

**Issue by mrkosima** [toomuchdesign/next-page-tester#188]
## 🐛 Bug Report

`useRouter` doesn't return `locale`, `locales` and `defaultLocale` from `next.config.js`

https://nextjs.org/docs/api-reference/next/router#router-object

## Expected behavior

`useRouter` returns:
-  `locales` and `defaultLocale` from `next.config.js`
- `locale` is equal to `defaultLocale` by default, can be configurable within `getPage({...})` props

**Comment by Meemaw** [comment]
Hi @mrkosima . This was added in `v0.24.0`. I still think `i18n` is not 100% implemented yet so if you face any problems fell free to open a new issue.
