### ISSUE TITLE
Don't enforce `props` field check on getInitialProps

### ISSUE THREAD

**Issue by toomuchdesign** [toomuchdesign/next-page-tester#19]
## 🐛 Bug Report

`missing "props" field` error should not be raised for `getInitialProps`.

## To Reproduce

Test a page which `getInitialProps` methods returns an object with missing `props` field.

## Expected behavior

`getInitialProps` should be able to return any object with no errors being thrown.

**Comment by toomuchdesign** [comment]
Wrong filing.

**Comment by gertie-sheshe** [comment]
Hi @toomuchdesign I am using your library to write integration tests for my NextJS app. I do run into the error described here and was wondering if there's a fix for it? I see you've closed the PR - could you point me to a resource that could help me if there's any? Thanks!

**Comment by toomuchdesign** [comment]
Hi @gertie-sheshe, could you provide a reproducible example of the behaviour you described? Are you sure the error is thrown while rendering a page with `getInitialProps` and not `getServerSideProps`?

**Comment by toomuchdesign** [comment]
I just verified that no `props` check is performed over `getInitialProps` return value. Can you confirm this @gertie-sheshe? Thank you 🙂
