### ISSUE TITLE
Source all environment variables in order to match Next

### ISSUE THREAD

**Issue by brettinternet** [toomuchdesign/next-page-tester#196]
## 🐛 Bug Report

The library only loads environment variables when they're prefixed with `NEXT_PUBLIC_`.

https://github.com/toomuchdesign/next-page-tester/blob/a483a65fd228587f16f2ced52909acc2b42d459d/src/setEnvVars.ts#L24-L26

However, this is different than Next's behavior. These "private" environment variables are indeed made available to SSR  and build functions, such as `getStaticProps`.

## Reproduction

Simply require an environment variable without a `NEXT_PUBLIC_` prefix in a `getStaticProps` function, for example. It will be undefined.

## Expected behavior

In order to match Next and expected functionality, these variables should be available to build and server runtime functionality.

## Jest patch

Have you patched Jest as [described here](https://github.com/toomuchdesign/next-page-tester#optional-patch-jest)?

- [ ] yes
- [x] no

## Run `npx envinfo --preset jest`

Paste the results here:

```bash
  System:
    OS: Linux 5.11 Arch Linux
    CPU: (20) x64 Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz
  Binaries:
    Node: 15.9.0 - ~/.nvm/versions/node/v15.9.0/bin/node
    npm: 7.5.3 - ~/.nvm/versions/node/v15.9.0/bin/npm
  npmPackages:
    jest: ^26.6.3 => 26.6.3
```

Thanks for your work on this very helpful test library.

**Comment by toomuchdesign** [comment]
Hi @brettinternet, thanks for reporting.
These are [our tests for environment variables](https://github.com/toomuchdesign/next-page-tester/blob/master/src/__tests__/environment-variables/environment-variables.test.tsx). Maybe we're not considering data fetching methods. Have you found issues anywhere else then data fetching methods?

**Comment by toomuchdesign** [comment]
Btw the library actually differentiates between client and server side env vars.
[Here](https://github.com/toomuchdesign/next-page-tester/blob/a483a65fd228587f16f2ced52909acc2b42d459d/src/server.ts#L14) is where the switch happens.

In order to investigate on this we'd need to reproduce the behaviour in tests.

**Comment by toomuchdesign** [comment]
Hi @brettinternet,
Tests weren't actually covering the scenario you mentioned, I updated them and -as far as I can see- they behave the way I understand Next.js works.

I created this PR https://github.com/toomuchdesign/next-page-tester/pull/197 for this.

Would you mind checking out the relevant branch and help us understand how `next-page-tester` doesn't align with Next.js when it comes to env vars? Thank you 🙌

**Comment by toomuchdesign** [comment]
The issue affected only `getStaticProps`. It was an actual missing implementation detail 👍

**Comment by brettinternet** [comment]
Hi @toomuchdesign, sorry for the delay. Thank you very much for your fix!
