### ISSUE TITLE
`TypeError: React.createContext is not a function` when using `react-select` on a page.

### ISSUE THREAD

**Issue by geritol** [toomuchdesign/next-page-tester#202]
## 🐛 Bug Report

Getting `TypeError: React.createContext is not a function` when using `react-select` on a page.
The app works fine both in dev and production mode.

## Reproduction

https://github.com/geritol/next-page-tester-bug-repro

## Jest patch

Have you patched Jest as [described here](https://github.com/toomuchdesign/next-page-tester#optional-patch-jest)?

- [x] yes (`jest-patch` branch)
- [x] no  (`main` branch)

## Run `npx envinfo --preset jest`

Paste the results here:

```bash
  Binaries:
    Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.19.0/bin/yarn
    npm: 7.7.6 - ~/.nvm/versions/node/v12.19.0/bin/npm
  npmPackages:
    jest: ^26.6.3 => 26.6.3 

```

**Comment by Meemaw** [comment]
Hi @geritol 👋 

Do you mind trying to set `sharedModules: ["react-select"]` option as a quick check?

**Comment by geritol** [comment]
Hi @Meemaw!
Sorry, I forgot to mention, that I have tryed that, and did not work.
I also tryed adding `@emotion/react` to shared. And also react itself. Which I think is there by default if I remember the code properly.

**Comment by toomuchdesign** [comment]
After investigating a bit it emerged that the `react` instance required from `node_modules/@emotion/react/dist/emotion-element-cb6e9ca7` returns `{}`.

**Comment by toomuchdesign** [comment]
Hi  @geritol,
the issue seems to be caused by Jest's `moduleDirectories` config option. Remove the option and tests should turn green again.

**Comment by geritol** [comment]
@toomuchdesign thanks a lot for your help on this!
My setup currently relies on having `"."` in `moduleDirectories`, and this is causing the bug. 

`@emotion/react` having `react` as a dependency satisfies

> scoped package that had the same subdirectory name as a non-scoped package (e.g. @my-scope/my-package relies on my-package as an external/peer dependency).

https://github.com/facebook/jest/issues/10498

This seems to be a pretty weird issue in Jest, it might be worth my time to look around on the Jest side of things if it can be fixed at some point in time.

Sorry for opening an issue with this, I was pretty sure this is a bug in `next-page-tester`. 
Thanks a lot again on your support on this one!

**Comment by toomuchdesign** [comment]
I've never heard of this :) I recently contributed to Jest, and I can say it was a very smooth experience. Totally worth a try if you're considering opening a PR 👍
