### ISSUE TITLE
i18n module missing it seems 

### ISSUE THREAD

**Issue by jyk2000** [toomuchdesign/next-page-tester#205]
## 🐛 Bug Report

I'm getting error as below when running the with this module.
`
Cannot find module 'next/dist/next-server/lib/i18n/normalize-locale-path' from 'node_modules/next-page-tester/dist/utils.js'

    Require stack:
      node_modules/next-page-tester/dist/utils.js
      node_modules/next-page-tester/dist/getPageObject/makeRouteInfo.js
      node_modules/next-page-tester/dist/getPageObject/index.js
      node_modules/next-page-tester/dist/page/getPageInfo.js
      node_modules/next-page-tester/dist/page/index.js
      node_modules/next-page-tester/dist/getPage.js
      node_modules/next-page-tester/dist/pure.js
      node_modules/next-page-tester/dist/index.js
      __tests__/HomeTest.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/next-page-tester/dist/utils.js:16:33)
`

## Reproduction

Please provide a link to a minimal GitHub repo reproducing the issue _(we won't be able to provide support otherwise)_.

## Expected behavior

NextJS expect i18n but next-page-tester lacking it

## Jest patch

Have you patched Jest as [described here](https://github.com/toomuchdesign/next-page-tester#optional-patch-jest)?

- [ ] yes
- [ x] no

## Run `npx envinfo --preset jest`

`npx: installed 1 in 0.885s

  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11900KF @ 3.50GHz
    Memory: 50.58 GB / 63.68 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
  Managers:
    pip3: 20.2.3 - C:\Python39\Scripts\pip3.EXE
  Utilities:
    Git: 2.31.1. - C:\Program Files\Git\mingw64\bin\git.EXE
  IDEs:
    VSCode: 1.55.2 - C:\Users\jyk20\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
    Visual Studio: 15.9.28307.1500 (Visual Studio Community 2017)
  Languages:
    Bash: 4.4.23 - C:\Program Files\Git\usr\bin\bash.EXE
    Perl: 5.32.1 - C:\Program Files\Git\usr\bin\perl.EXE
    Python: 3.9.4 - C:\Python39\python.EXE
  Browsers:
    Edge: Spartan (44.19041.906.0), Chromium (90.0.818.46)
    Internet Explorer: 11.0.19041.1
`

**Comment by toomuchdesign** [comment]
It seems that your project is using non matching version of `next` and `next-page-tester`. See [here](https://github.com/toomuchdesign/next-page-tester#nextjs-versions-support).

Closing since not enough information is provided to give support.
