### ISSUE TITLE
Proper way to do full-page snapshot tests

### ISSUE THREAD

**Issue by vlad-elagin** [toomuchdesign/next-page-tester#207]
## 💬 Questions and Help

Hello!
I wander what is the proper way to do snapshot tests with this library. In unit tests with `react-testing-library` I usually use `asFragment` to get DOM representation, but there is no such method in its `screen`.

Anyway, thanks for this lib. Great tool 🙏

**Comment by toomuchdesign** [comment]
Hi @vlad-elagin, you can use `react-testing-library` along with `next-page-tester`.

**Comment by vlad-elagin** [comment]
@toomuchdesign but I can't get document fragment via `react-testing-library` since rendering is being performed by `next-page-tester`.

But I've found a way, probably someone will need this:
```
const { html } = serverRenderToString();
const formattedSnapshot = prettier.format(html, {
  parser: "html",
});
expect(formattedSnapshot).toMatchSnapshot();
```

**Comment by Meemaw** [comment]
@vlad-elagin What is `prettier` here? Is it actually the `prettier` package? Do you mind opening a PR and adding this to the examples? As you mentioned, this might probably be useful to others.

**Comment by vlad-elagin** [comment]
@Meemaw yep, it is `prettier` package. It [can](https://prettier.io/docs/en/api.html) be used programmatically.

>Do you mind opening a PR and adding this to the examples?

Of course

**Comment by vlad-elagin** [comment]
Also, can you write contributing and development guide? I was pretty surprised when lintings and checks started during `npm i` 😁
