### ISSUE TITLE
Custom wrapper for _app

### ISSUE THREAD

**Issue by vlad-elagin** [toomuchdesign/next-page-tester#210]
## 🚀 Feature Proposal

It would be great to have a way to customize _app. In source code I've seen that there is already a wrapper for `Page` and it have types for custom app.

## Motivation

In my project we use `next-translate` (via webpack plugin) and keep some layout  (header, footer) `in _app.tsx`. AFAIK I can't use webpack plugin to load locales during testing with `next-page-tester`, so I need to wrap app in provider and load them manually. I tried to wrap `Page` by using `wrapper.Page` but then my header and footer are left without locales.

I can try to implement this and submit a PR but I definitely would need help with it. I've already tried to modify this package but with no luck.

## Example

Something like this:
```typescript
const { render } = await getPage({
    route: "/",
    useDocument: true,
    wrapper: {
        App: App => {
             return appWithI18N(App);
        },
    },
});
```
or like this:
```typescript
const { render } = await getPage({
    route: "/",
    useDocument: true,
    wrapper: {
        App: App => {
             App.getInitialProps = async () => ({
                pageProps: {
                    ...(await loadNamespaces()),
                }
             });

             return App;
        },
    },
});
```

**Comment by toomuchdesign** [comment]
Hi @vlad-elagin,
I remember we initially considered introducing a wrapper targeting `App`, but I probably pushed it back since it was not strictly necessary to fix the specific issue we were facing :)

If @Meemaw agrees, we can totally proceed with a PR extending current `wrapper` option.

**Comment by Meemaw** [comment]
When we implemented `wrapper` option for `Page` I intentionally wanted it to be an object so we can add support for wrapping at other levels (e.g. `App` and `Document`). At the time we didn't have a use-case for `App` level wrapping so we left it out.

I can see how wrapping at `Page` level would leave the `_app` locales untranslated, therefor pull request for this is welcome 😉 If you have any issues let me know. I can also implement this sometime this week (probably end of it).

**Comment by toomuchdesign** [comment]
Super! Glad to support you @vlad-elagin in case you wanted to give to a try. I'd suggest to extend [wrapper tests](https://github.com/toomuchdesign/next-page-tester/tree/master/src/__tests__/wrapper) first and then move on to the actual implementation.

**Comment by vlad-elagin** [comment]
@evocateur did you manage to get this work?

**Comment by evocateur** [comment]
@vlad-elagin Yep! Gonna open the PR momentarily.
