### ISSUE TITLE
next-auth/client issue 

### ISSUE THREAD

**Issue by jyk2000** [toomuchdesign/next-page-tester#214]
## 💬 Questions and Help

I'm using next-auth/client Provider component to wrap _app.js 
And getting below error when calling getPage() funciton. 
```
Provider(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
```
This should be handled by the plugin author right?

**Comment by toomuchdesign** [comment]
Closing for to lack of information.
