### ISSUE TITLE
The steps to patch jest don't work while using Yarn v2

### ISSUE THREAD

**Issue by markcnunes** [toomuchdesign/next-page-tester#219]
## 🐛 Bug Report

It is not exactly a bug, but a suggestion to add instructions on how to patch jest while using Yarn v2.

The [steps to patch jest](https://github.com/toomuchdesign/next-page-tester#setting-up-your-dev-environment) don't work on projects using Yarn v2.

[Yarn v2 supports builtin patches](https://yarnpkg.com/cli/patch)

I didn't know about Yarn v2 supporting it so it took me a while to figure out those steps in README wouldn't work on my project.

Here are the steps I had to follow to patch Jest:

1. `yarn patch jest-runtime`. 
2. The previous command will show the following message `You can now edit the following folder: ...`, open the folder to edit  the file `build/index.js`
3. Once you are done run `yarn patch-commit`. If you use an IDE that does any kind of auto-format on save, you’ll want to bypass this. As you’ll see in a moment, the patch-commit command is going to create a very specific diff file, and you don’t want it cluttered with cosmetic changes. The output should look like this:

```patch
diff --git a/build/index.js b/build/index.js
index 1c13b1d28cbc6785e62b14bfdea7522c48eef5c6..46dabeb7f965f4a5d011b70dd5b5d1451300833b 100644
--- a/build/index.js
+++ b/build/index.js
@@ -715,13 +715,10 @@ class Runtime {
     ) {
       moduleRegistry = this._internalModuleRegistry;
     } else {
-      if (
-        this._moduleRegistry.get(modulePath) ||
-        !this._isolatedModuleRegistry
-      ) {
-        moduleRegistry = this._moduleRegistry;
-      } else {
+      if (this._isolatedModuleRegistry) {
         moduleRegistry = this._isolatedModuleRegistry;
+      } else {
+        moduleRegistry = this._moduleRegistry;
       }
     }
 
```
4. Save the above code in the following file `patches/jest-runtime.patch`.
5. Add the resolution to your package.json.

```json
{

  "dependencies": {
    "jest": "^26.6.3",
  },
  "resolutions": {
    "jest-runtime": "patch:jest-runtime@26.6.3#./patches/jest-runtime.patch"
  },
}
```

6. Now re-run yarn and restart your dev environment

### Source
I used the following article as a reference: [How to patch an npm package with yarn patch](https://ryanelainska.com/blog/how-to-patch-an-npm-package-with-yarn-patch).

**Comment by toomuchdesign** [comment]
Hi @markcnunes,
thanks for documenting this. Doesn't `patch-package` work at all with Yarn 2, not even with `postinstall-postinstall` as documented [here](https://github.com/ds300/patch-package#why-use-postinstall-postinstall-with-yarn)?

**Comment by markcnunes** [comment]
Hi @toomuchdesign 
It didn't work at all. The Plug'n'Play provided by Yarn v2 makes node_modules obsolete.
Here is an issue related to it [PnP (Yarn) support](https://github.com/ds300/patch-package/issues/83). On that same issue, there is a [comment](https://github.com/ds300/patch-package/issues/83#issuecomment-569256924) for when `yarn patch` has been introduced to fix that problem.

**Comment by toomuchdesign** [comment]
Docs updated. Thanks @markcnunes!
