### ISSUE TITLE
Custom appProps in custom _app are not being passed to App component

### ISSUE THREAD

**Issue by madeuz** [toomuchdesign/next-page-tester#220]
consider following:

```javascript
export default function CustomApp({ Component, pageProps, customProps }) {
  // customProps is undefined here
  return (
    <CustomProvider {...customProps}>
      <Component {...pageProps} />
    </>
  )
}

CustomApp.getInitialProps = async (appContext) => {
  const appProps = await App.getInitialProps(appContext)
  const customProps = { someData: true }
  return { ...appProps, customProps }
}
```

only `pageProps` are passed down and merged with child page, other app props are dropped

**Comment by toomuchdesign** [comment]
Hi @madeuz,
would you mind pointing out the relevant documentation or type definition from `customProps`?

**Comment by Meemaw** [comment]
> Hi @madeuz,
> would you mind pointing out the relevant documentation or type definition from `customProps`?

I think this is just an example prop defined by user. Could be anything.

**Comment by madeuz** [comment]
> > Hi @madeuz,
> > would you mind pointing out the relevant documentation or type definition from `customProps`?
> 
> I think this is just an example prop defined by user. Could be anything.

Exactly, `customProps` is just example name, could be any. And it should be passed to CustomApp. Currently it just merges `pageProps` of `appProps` into pages' `props` skipping other app props.

https://github.com/toomuchdesign/next-page-tester/blob/0455911c0f523102ee324a305ab0714f3cc02552/src/_app/render.tsx#L55

should be something like
```javascript
  return <UserEnhancedApp Component={UserEnhancedPage} pageProps={pageProps} {...appProps} />;
```

with 
```javascript
  const { pageProps: appInitialPageProps, ...restOfAppInitialProps } = appInitialProps;
  
  return { ...pageData, appProps: restOfAppInitialProps };
```

added maybe here:
https://github.com/toomuchdesign/next-page-tester/blob/0455911c0f523102ee324a305ab0714f3cc02552/src/fetchData/fetchRouteData.ts#L16-L21

and passed down here:
https://github.com/toomuchdesign/next-page-tester/blob/0455911c0f523102ee324a305ab0714f3cc02552/src/page/makePageElement.ts#L11-L15
and here:
https://github.com/toomuchdesign/next-page-tester/blob/0455911c0f523102ee324a305ab0714f3cc02552/src/getPage.tsx#L126-L131

**Comment by Meemaw** [comment]
@madeuz  Since you already investigated our code a bit, perhaps you can take a stab at implementing this? 💪 

If not, this will probably be implemented sometime in the future but cant give any exact dates/promises.
