### ISSUE TITLE
`ReferenceError: setImmediate is not defined` under Jest 27

### ISSUE THREAD

**Issue by fracture91** [toomuchdesign/next-page-tester#221]
## 🐛 Bug Report

After updating to Jest 27, `await getPage({ route: "/", useDocument: true, useApp: true })` is producing the following error:

```
    ReferenceError: setImmediate is not defined

      4 | describe("Homepage", () => {
      5 |   it("renders nicely", async () => {
    > 6 |     const { render } = await getPage({ route: "/", useDocument: true, useApp: true })
        |                        ^
      7 |     render()
      8 |     expect(screen.getByText("Welcome to")).toBeVisible()
      9 |   })

      at AsyncReader.read (node_modules/@nodelib/fs.walk/out/readers/async.js:26:9)
      at StreamProvider.read (node_modules/@nodelib/fs.walk/out/providers/stream.js:30:22)
      at ReaderStream.walkStream [as _walkStream] (node_modules/@nodelib/fs.walk/out/index.js:25:21)
      at ReaderStream.dynamic (node_modules/fast-glob/out/readers/stream.js:14:21)
      at ProviderAsync.api (node_modules/fast-glob/out/providers/async.js:23:33)
      at node_modules/fast-glob/out/providers/async.js:15:33
      at ProviderAsync.read (node_modules/fast-glob/out/providers/async.js:14:16)
          at Array.map (<anonymous>)
      at getWorks (node_modules/fast-glob/out/index.js:58:18)
      at Object.FastGlob [as default] (node_modules/fast-glob/out/index.js:10:19)
      at Object.getPagePaths [as default] (node_modules/next-page-tester/dist/getPageObject/getPagePaths.js:12:44)
      at Object.getRouteInfo [as default] (node_modules/next-page-tester/dist/getPageObject/getRouteInfo.js:13:51)
      at Object.getPageObject (node_modules/next-page-tester/dist/getPageObject/getPageObject.js:13:51)
      at Object.getPageInfo (node_modules/next-page-tester/dist/page/getPageInfo.js:13:46)
      at getPage (node_modules/next-page-tester/dist/getPage.js:65:51)
      at Object.<anonymous> (__tests__/next-page-tester.js:6:24)
```

It's from deep inside `fast-glob`, but it might be related to the way next-page-tester messes with `window`?

## Reproduction

This specific branch will cause the error after `npm install && npm test`: https://github.com/fracture91/next-page-tester-hook-error/tree/jest27

## Expected behavior

No error occurs and my tests pass :)

## Jest patch

Have you patched Jest as [described here](https://github.com/toomuchdesign/next-page-tester#optional-patch-jest)?

- [ ] yes
- [x] no, because Jest 27 allegedly has that patch already

## Run `npx envinfo --preset jest`

Paste the results here:

```bash
  System:
    OS: macOS 11.2.3
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 15.8.0 - /opt/homebrew/bin/node
    Yarn: 1.22.5 - /opt/homebrew/Cellar/yvm/4.1.1/shim/yarn
    npm: 7.5.0 - /opt/homebrew/bin/npm
  npmPackages:
    jest: ^27.0.0 => 27.0.1 
```

**Comment by toomuchdesign** [comment]
Welcome back @fracture91,
I haven't had the time to try Jest v27 out, it could be related to the fact that `jest-environment-jsdom` seems to [not mock `setImmediate` and `clearImmediate` anymore](https://github.com/facebook/jest/pull/11222/files?file-filters%5B%5D=.lock&file-filters%5B%5D=.ts). I currently don't have the full picture about what actually happens in  `jest-environment-jsdom`, though.

Do you have the chance of investigating this path?

**Comment by massimeddu-sonic** [comment]
Same issue here after upgrading to Jest 27.

**Comment by toomuchdesign** [comment]
I understand that `jest-environment-jsdom` didn't actually mock Node's globals but made them available in jsdom environment. Since Jest 27 only the globals actually existing in browser environment are let through.

If this assumption is correct we might consider replacing `fast-glob` with something else or explicitly making `setImmediate` available.

**Comment by toomuchdesign** [comment]
@fracture91 would you have the chance to try and replace `fast-glob` with `fast-glob` and open a PR in case in case it solves the issue? Happy to provide guidance.

**Comment by fracture91** [comment]
> @fracture91 would you have the chance to try and replace `fast-glob` with `fast-glob` and open a PR in case in case it solves the issue? Happy to provide guidance.

Sure, it doesn't look too difficult (🤞).  I'll probably have time to take a stab at it over the next couple of days.

**Comment by Meemaw** [comment]
I think its better to shim it using https://github.com/YuzuJS/setImmediate

I tried that and it fixed the issue (e.g. just imort it in our setup), but there are still some issues with jest after that one is fixed.

**Comment by toomuchdesign** [comment]
Hi @Meemaw, we might definitely try and setup a jest27 branch as soon as we have time to do so.

In regard of shimming `setImmediate`, shouldn't we consider trying first to leave Jest environment untouched by removing `setImmediate` from our call stack?

**Comment by Meemaw** [comment]
Sure, If we find a replacement that works well and passes all our tests. `"replace fast-glob with fast-glob"` <- some typo here?

**Comment by toomuchdesign** [comment]
Hihi, fixed my typo.

**Comment by toomuchdesign** [comment]
I set up a branch to gather the updates related to Jest 27.
https://github.com/toomuchdesign/next-page-tester/pull/223

**Comment by toomuchdesign** [comment]
Let's move the discussion [here](#223 ).

**Comment by filipkowal** [comment]
@toomuchdesign I've stumbled upon the same error using 0.25 version. I guess #223 that seems to fix it is merged to newer versions only, right?

```System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
  npmPackages:
    jest: 27.0.6 => 27.0.6 ```

**Comment by toomuchdesign** [comment]
Only last versions of `jest`, `next` and `next-page-tester` are supported.
