### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by ThallyssonKlein** [toomuchdesign/next-page-tester#229]
## 🐛 Bug Report

I'm having a timeout when I try to run tests rendering a page.

## Reproduction

https://github.com/ThallyssonKlein/next-page-tester-issue

## Expected behavior

I would expect not to have a timeout when rendering a page

## Jest patch

Have you patched Jest as [described here](https://github.com/toomuchdesign/next-page-tester#optional-patch-jest)?

- [X] yes
- [ ] no

## Run `npx envinfo --preset jest`

Paste the results here:

```bash
System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
  Binaries:
    Node: 12.0.0 - ~/.config/nvm/versions/node/v12.0.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.12.0 - ~/.config/nvm/versions/node/v12.0.0/bin/npm
```

**Comment by toomuchdesign** [comment]
Hi @ThallyssonKlein,
not sure whether related to the issue you reported, but we've never considered the use case of a Next.js application run by CRA tools. Have you tried to remove CRA and setup the project as a standalone Next app?
