### ISSUE TITLE
Support server side redirects

### ISSUE THREAD

**Issue by Meemaw** [toomuchdesign/next-page-tester#23]
## 🚀 Feature Proposal

We are using SSR with "authenticated" middleware to protect authenticated routes.

This middleware will check if user is authenticated and if not redirect him to another page, e.g. /login

The logic inside `getServerSideProps` might look something like this:

```ts
export const getServerSideProps: GetServerSideProps<Props> = async (
  context
) => {
  if (someSpecialCase) {
      context.res.writeHead(302, { Location: "/login" });
      context.res.end();
      return undefined;
  }
}
```

This means that the I would expect `/login` page to be returned from the `getPage` function.

**Comment by toomuchdesign** [comment]
Hi @Meemaw,
Next 10 introduced [`redirect` and `notFound`  support](https://nextjs.org/blog/next-10#redirect-and-notfound-support-for-getstaticprops--getserversideprops) for `getServerSideProps`.

I'd be inclined toward targeting Next v10 (#20) and adding support for `redirect` and `notFound` result objects. How do you see it?

**Comment by Meemaw** [comment]
Totally agree. That is much easier to implement and a way forward 👍

**Comment by toomuchdesign** [comment]
Currently we already detect result objects lacking `props` field (like `redirect` and `notFound`). next-page-tester will throw [this error](https://github.com/toomuchdesign/next-page-tester/blob/v0.7.0/src/fetchData/fetchPageData.ts#L52) and attach the returned object in `error.payload`.

In some circumstances this might also be good enough depending on the testing approach. Would it fit your testing case?

Since Next.js would trigger an actual server side redirect, we should consider how to translate it into DOM logic carefully since there is currently no way to inform tests about the occurred redirect.

**Comment by Meemaw** [comment]
I would expect not having to catch anything or look into the returned object. Is it not possible that when `redirect` is present -- redirected page is returned?

**Comment by toomuchdesign** [comment]
It should be definitely feasible (even though I still have to find out how). I was considering every option before taking a decision :)

The approach you suggest is definitely closer to an e2e testing experience. Which is interesting.

**Comment by Meemaw** [comment]
Yeah, its very high level and abstract, but I think this is the experience most people would expect and would probably suit most of the use cases. I like the fact that there is no implementation details leaked, you don't even have to know its NextJS underneath.

In theory, library could have multiple "levels" of abstraction and if more fine grained control would be needed some lower level API would be used.

Just thinking out loud: there could be some lower level API exposed that could return more stuff, e.g. page itself + "props", "redirect"... and it implementation would be used internally by the "higher" level.
```js
// ignore the name. This page would perhaps not be resolved to the redirect automatically but the user would have to do it in code manually
const { page, props, redirect } = await getPageLowerApi({
   route: '/private/page',
});

if(redirect) {
   const { page: redirectedPage } = await getPageLowerApi({ route: redirect })
   render(redirectedPage)
}
```

**Comment by toomuchdesign** [comment]
I love the idea of returning an object to destructure. It would give us quite a lot of flexibility. Let's go for it.

For now it might return an object with just the `page` prop.

**Comment by Meemaw** [comment]
Gave it some more though, I think the following API makes sense and is flexible:

```ts
const { page, props, redirect } = await getPage({ route: '/' })
await screen.findByText("Login") // we are on login page

const { props, redirect } = await getPage({ route: '/', followRedirects: false })
expect(redirect).toEqual('/login') // we are not on login page, but we can make assertions on the redirect object
```

**Comment by toomuchdesign** [comment]
From v.10 fetching methods can return:
- object with `props`
- object with `redirect`
- object with `notFound`

...but in future they might return a wider set of objects.

In order not make too many assumption, what if we returned the object returned by the fetching method as it is, instead specific `props` or `redirect` fields?

The API would be a bit lower level but still quite straightforward.

```js
const { pageData } = await getPage({ route: '/', followRedirects: false })
expect( pageData.redirect ).toEqual('/login')
const { page } = await getPage({ route: pageData.redirect })
```
This would support for free `notFound` objects:

```js
expect( pageData.redirect ).toBe(true)
```
