### ISSUE TITLE
Need to patch Jest v27?

### ISSUE THREAD

**Issue by JChiaramonte7** [toomuchdesign/next-page-tester#232]
## 💬 Questions and Help

Running into issues with Styled Components and React getting caught on the hydrate step. Went to go patch my jest before opening a full blown issue here. But do we still need to patch Jest v27?

![image](https://user-images.githubusercontent.com/4015977/123315824-26097a80-d4fa-11eb-9811-8421fd922012.png)

**Comment by toomuchdesign** [comment]
Hi @JChiaramonte7,
nope, `next-page-tester` runs with Jest v27 without patch since previously patched code made it into Jest 27.
