### ISSUE TITLE
image domains not loaded from next.config.js

### ISSUE THREAD

**Issue by derweili** [toomuchdesign/next-page-tester#234]
## 🐛 Bug Report

I created the nextjs project with `npx create-next-app`. I added Jest and next-page-tester.

When trying to render a Page that uses `next/image` I get following Error:

```bash
Error: Uncaught [Error: Invalid src prop (https://picsum.photos/id/238/200/300) on `next/image`, hostname "picsum.photos" is not configured under images in your `next.config.js`
```
I don't get this error when using `yarn dev` or `yarn build && yarn start`

My next.config.js looks like this

```js
module.exports = {
  reactStrictMode: true,
  images: {
    domains: ['picsum.photos']
  }
}
```

## Reproduction

Create a next.js project. Add Jest + next-page-tester. Use the `next/image` component with an image from an external Domain and add this domain to next.config.js.

## Expected behavior

next-page-tester should load the next.config.js and accept the image domains.

## Jest patch

Have you patched Jest as [described here](https://github.com/toomuchdesign/next-page-tester#optional-patch-jest)?

- [ ] yes
- [x] no

## Run `npx envinfo --preset jest`

Paste the results here:

```bash
  System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.4.0 - ~/.nvm/versions/node/v16.4.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.0/bin/yarn
    npm: 7.18.1 - ~/.nvm/versions/node/v16.4.0/bin/npm
  npmPackages:
    jest: ^27.0.5 => 27.0.5 
```

**Comment by toomuchdesign** [comment]
Hi @derweili, thanks for reporting.
It definitely seems a missing feature probably introduced with v11. We should reproduce the issue in tests and then see how to extend the existing logic to cover this external domain scenario.

I can't tell when I'll be able to work on this, though. As usual we're open to contributions and glad to provide reviews/guidance.

**Comment by toomuchdesign** [comment]
I've reproduced the issue in #236.
