### ISSUE TITLE
Emotion configuration

### ISSUE THREAD

**Issue by diogoredin** [toomuchdesign/next-page-tester#237]
## 🐛 Bug Report

```
"@emotion/jest": "^11.3.0",
"@emotion/react": "^11.4.0",
"@emotion/styled": "^11.3.0",
"jest": "^27.0.6",
"next-page-tester": "^0.27.0",
```

`    Warning: Did not expect server HTML to contain a <style> in <div>.
        at main
        at Styled(main)`

`    Warning: Did not expect server HTML to contain a <style> in <div>.
        at p
        at Styled(span)`

## Reproduction

Private at the moment, unfortunately.

## Expected behavior

Used `src/__tests__/third-party/emotion/emotion.test.ts` as a base:

```jsx
describe('<Home />', () => {
  it('renders home page', async () => {
    const { render } = await getPage({
      route: '/',
      useDocument: true,
      useApp: true,
    })

    render()
  })
```

The following code causes the warning above:

```jsx
const Container = styled.main`
  padding: 0;
`
```

## Jest patch

Using v27.

## Run `npx envinfo --preset jest`

Paste the results here:

```bash
  System:
    OS: macOS 11.2.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
  npmPackages:
    jest: ^27.0.6 => 27.0.6
```

Any help or indication of configurations necessary for the testing to work with emotion is appreciated 🙏

**Comment by toomuchdesign** [comment]
Hi @diogoredin,
we have a test case specifically targeting emotion:
https://github.com/toomuchdesign/next-page-tester/tree/master/src/__tests__/third-party/emotion

You can try to update/extend it if doesn't cover your scenario.
