### ISSUE TITLE
Support multi-tenant applications

### ISSUE THREAD

**Issue by skilesare** [toomuchdesign/next-page-tester#25]
Will this support multi-tenant application on next.js?  My rendering depends on the host. For example: test1.myapp.com/ renders differently than test2.myapp.com.  The site copy is usually loaded by the db in getInitialProps:

```
@getInitialProps: (context)=>
    sessionUtils = new SessionUtils.SessionUtils(this.session)
    #console.log 'calling get brand info', context.req.headers
    brandInfo = await sessionUtils.getBrandInfo(context.req.headers)


    return
      brandInfo: brandInfo
```
Will doing this work?

```
const Page = await getPage({
      route: 'http://test1.myapp.com:3000/blog/1',
    });

    render(Page);
```

**Comment by toomuchdesign** [comment]
Hi @skilesare,
`route` currently expects a relative path with leading slash (`/path`) just like Next's `Link` does.

If your page relies on some specific `req` object values, you might consider mocking them using  the `req` option.

If you had different take about how we might handle this I'm happy to listen.

**Comment by skilesare** [comment]
Cool.  So I see that the signature for getPage is:

```
export default async function getPage({
  route,
  nextRoot = defaultNextRoot,
  req = (req) => req,
  res = (res) => res,
  router = (router) => router,
  useCustomApp = false,
}
```

So I can just jam in a mock for req and it should get passed to the page?  If I check reqs there it should have what I pass in?

**Comment by toomuchdesign** [comment]
`req` option accepts a function which:

- receives the default `req` object created for requested page
- returns the `req` object that will be used to render the page

**Comment by Meemaw** [comment]
@toomuchdesign I believe it's not possible to set headers on that req object which is a very common need, e.g. for cookies. In that case this is not really closed.
