### ISSUE TITLE
Tests with catch-all-routes fail

### ISSUE THREAD

**Issue by jonasatmonday** [toomuchdesign/next-page-tester#250]
## 🐛 Bug Report

Hello,
we tried to use next-page-tester in our project but get the following issue when running a test that tries to get a page with a catch-all-route:

```bash
Catch-all must be the last part of the URL.

      at UrlNode._insert (node_modules/next/shared/lib/router/utils/sorted-routes.ts:79:13)
      at UrlNode._insert (node_modules/next/shared/lib/router/utils/sorted-routes.ts:194:8)
      at UrlNode.insert (node_modules/next/shared/lib/router/utils/sorted-routes.ts:9:10)
      at node_modules/next/shared/lib/router/utils/sorted-routes.ts:213:46
          at Array.forEach (<anonymous>)
      at Object.getSortedRoutes (node_modules/next/shared/lib/router/utils/sorted-routes.ts:213:19)
      at Object.getPagePaths [as default] (node_modules/next-page-tester/dist/getPageObject/getPagePaths.js:14:28)
      at Object.getRouteInfo [as default] (node_modules/next-page-tester/dist/getPageObject/getRouteInfo.js:13:23)
      at Object.getPageObject (node_modules/next-page-tester/dist/getPageObject/getPageObject.js:13:23)
      at Object.getPageInfo (node_modules/next-page-tester/dist/page/getPageInfo.js:13:24)
      at getPage (node_modules/next-page-tester/dist/getPage.js:66:38)
```

This is our test:

```typescript
test('first integration test', async () => {
    const { render } = await getPage({
        route: '/test/page',
    });
    render();

    await waitFor(() => {
        expect(screen.getByText('I am a test page')).toBeInTheDocument();
    });
});
```

And this is our `index.tsx` at` /pages/[...pathSegments]/index.tsx`:

```typescript
import {NextPage} from "next";

const Home: NextPage = () => {
    return (
        <div>I am a test page</div>
    );
}

export default Home;
```

## Reproduction

I reproduced the issue with a new next JS minimal repo: https://github.com/jonasatmonday/next-page-tester-minimal-repo

Simply check out the develop branch, run `yarn install` and then try to run the test with `yarn jest`.

The catch-all-route works perfectly fine when starting the next dev server with `yarn dev` and opening the page at http://localhost:3000/test/page.

## Expected behavior

I expect tests with catch-all-routes to work and not throw the described error. Our project works with a CMS so all our pages have highly dynamic paths.

## Jest patch

Have you patched Jest as [described here](https://github.com/toomuchdesign/next-page-tester#optional-patch-jest)?

- [ ] yes
- [X] no

Not required because I use jest 27.1.0

## Run `npx envinfo --preset jest`

Paste the results here:

```bash
npx: installed 1 in 1.336s

  System:
    OS: macOS 11.5.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.1/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.15.1/bin/npm
  npmPackages:
    jest: ^27.1.0 => 27.1.0 
```

**Comment by toomuchdesign** [comment]
Hi @jonasatmonday,
the error you get seems quite explanatory:

```
Catch-all must be the last part of the URL.
```

Next.js doesn't support catch-all route segments in the middle of a page path. The error comes from an utility of Next.js itself.

It seems that there's a working undocumented edge case related to `[...catch-all]/index` routes.

As a temporary solution I'd suggest to declare Next.js as stated in documentation:

```
/pages/[...pathSegments]/index.tsx. --> /pages/[...pathSegments].tsx

```

**Comment by jonasatmonday** [comment]
Hi @toomuchdesign,
thanks for your response! Your suggestion solved our catch-all-issue. And I guess it really is an working undocumented edge case - we never experienced an issue with those routes in our Next.js app.

Best regards,
Jonas
