### ISSUE TITLE
Mocking router in index page

### ISSUE THREAD

**Issue by lsbyerley** [toomuchdesign/next-page-tester#257]
## 🐛 Bug Report

I am a creating a simple test for the `pages/index.js` file in a nextjs application. In my `_app.js` file I am using the router variable to key off of `router.events`. When using the `getPage` function from this library, `router.events` is undefined. Forgive me if i'm not understanding the docs, but am I not using router correctly in `getPage`?

The test fails with this error: `TypeError: routerEnhancer is not a function`

```
// index.test.js
import { getPage } from 'next-page-tester';
import { screen } from 'test-utils';

describe('Home page', () => {
  it('renders home page', async () => {
    const { render } = await getPage({
      route: '/',
      router: {
        events: {
          on: jest.fn(),
          off: jest.fn(),
        },
      },
    });

    render();
    expect(screen.getByText('Home,')).toBeInTheDocument();
  });
});
```

```
//_app.js
import { useEffect } from 'react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const App = ({ Component, pageProps, router }) => {
  useEffect(() => {
    const handleRouteChange = (url) => {
      console.log('LOG: route change', url);
    };
    router.events.on('routeChangeComplete', handleRouteChange);
    return () => {
      router.events.off('routeChangeComplete', handleRouteChange);
    };
  }, [router.events]);

  return (
    <>
      <Header />
      <Component {...pageProps} />
      <Footer />
    </>
  );
};

export default App;
```

## Jest patch

Have you patched Jest as [described here](https://github.com/toomuchdesign/next-page-tester#optional-patch-jest)?

- [] yes
- [ ] no

## Run `npx envinfo --preset jest`

```
  System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
  npmPackages:
    jest: 27.1.0 => 27.1.0 
```

**Comment by toomuchdesign** [comment]
Hi @lsbyerley,
[`router` option](https://github.com/toomuchdesign/next-page-tester#options) expects a function returning the mocked router object.

**Comment by lsbyerley** [comment]
@toomuchdesign Thanks for your reply.. that is what I thought also but even using it that way still results in this error:

```
  TypeError: Cannot read property 'events' of undefined

      14 |       router.events.off('routeChangeComplete', handleRouteChange);
      15 |     };
    > 16 |   }, [router.events]);
```

```
const { render } = await getPage({
      route: '/',
      router: () => ({
        events: {
          on: jest.fn(),
          off: jest.fn(),
        },
      }),
    });
```

**Comment by toomuchdesign** [comment]
Yep, `router` option function should extend the default router object provided as argument:

```
router: (router) => {
  router.events.on = jest.fn();
  router.events.off = jest.fn();
  return router;
},
```

[Here](https://github.com/toomuchdesign/next-page-tester/blob/v0.28.0/src/router/makeRouterMock.ts#L16) is where router mock is created.

**Comment by lsbyerley** [comment]
@toomuchdesign router continues to be undefined for me when logging its value in App.js when running the test. Strange
