### ISSUE TITLE
Context providers in wrapper.App not setting Context value on server render

### ISSUE THREAD

**Issue by otaviosoares** [toomuchdesign/next-page-tester#274]
## 🐛 Bug Report

Hello, I'm trying to test a page without using my _app component so I can mock the provider. I'm using the wrapper option, but my hook keeps throwing errors like there's no provider there. I can see that the provider is being used but have no clue what's going on.

Here's a contrived example (full version in the repo):

```js
// pages/index.js
import { useEffect } from 'react'
import { useTestHook } from '../test-hook'

export default function Home() {
  const {someFn} = useTestHook()
  useEffect(() => {
    someFn()
  }, [someFn])
  return (
    <div>
      ....
    </div>
  )
}
```

```js
// test-hook.js
export const useTestHook = () => {
  const test = useContext(Context)
  if (test === undefined) throw new Error(`useTestHook must be used within a TestHookProvider`)
  return test
}
```

```js
// test
import {getPage} from 'next-page-tester'
import { TestHookProvider } from '../test-hook'

function myMockedFn() {
  console.log('mocked version')
}

test('should render', async() => {
  const { render } = await getPage({ route:'/', useApp: false, wrapper: {
    App: App => appProps => 
      <TestHookProvider value={{someFn: myMockedFn}}>
        <App {...appProps} />
      </TestHookProvider>
  } })
  render()
})
```

Any help would be appreciated. Thanks

## Reproduction

Repo: https://github.com/otaviosoares/next-page-tester-bug
Just run `npm install` and `npm test`

## Expected behavior

Providers added to wrapper function should work.

## Jest patch

Have you patched Jest as [described here](https://github.com/toomuchdesign/next-page-tester#optional-patch-jest)?

- [ ] yes
- [x] no

## Run `npx envinfo --preset jest`

Paste the results here:

```bash
  System:
    OS: macOS 11.5.2
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v16.10.0/bin/yarn
    npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
  npmPackages:
    jest: ^27.3.0 => 27.3.0 
```

**Comment by toomuchdesign** [comment]
Hi @otaviosoares,
tests seems to seems to turn green when a default provider value is supplied ad provider initialization, like:

```
React.createContext({ someFn });
```

**Comment by toomuchdesign** [comment]
Providers works (see [wrapper tests](https://github.com/toomuchdesign/next-page-tester/blob/master/src/__tests__/wrapper/wrapper.test.tsx)) and setting a default provider value at initialization time is not weird.

The repro fails because of the error thrown by the [custom hook](https://github.com/otaviosoares/next-page-tester-bug/blob/main/test-hook.js#L7) which expects provider value not to be undefined.

The thing is that the repro sets a default provider value. indirectly through `Context.Provider`. There might be a slightly different execution cycle when using `wrapper`, I currently can't say.

**Comment by toomuchdesign** [comment]
Some extra context (ah-ah): it seems that context provider supplied with `wrapper.App` is not able to set context value when the page is rendered in server mode. We might try to update wrapper tests in order to facilitate a possible solution.
