### ISSUE TITLE
Implement an alternative way to find Next.js root path by first looking at next.config.js, then package.json

### ISSUE THREAD

**Issue by jbmusso** [toomuchdesign/next-page-tester#275]
## 🚀 Feature Proposal

Find Next.js root folder by first looking at a possibly present `next.config.js` file, then `package.json`.

## Motivation

In a mono repository configuration in which applications are very likely to be nested in subfolders, looking for a `package.json` may not be the most reliable way to find Next.js root repository; as far as I understand, this is `find-root` package default behavior, which `next-page-tester` uses internally.
The project we use currently uses a `nx` monorepo which comes with a single `package.json` file located at the root of the git repository. `next-page-tester` shouldn't be aware of build tools, though this change could improve the developer experience (while most likely being a breaking change).

Looking for these files in the following order may be more reliable:
1. `next.config.js`
2. `package.json`

Currently, we're doing the following:

```typescript
import findRoot from 'find-root';

const nextRoot = findRoot(__dirname, function (dir) {
  return fs.existsSync(path.resolve(dir, 'next.config.js'));
});

return getPage({
    nextRoot,
    // ...
  });
```
This is fine and works, though we have to add `find-root` as a dependency. Not a big deal per se, it's all about the amount of customization `next-page-tester` should support.
Alternatively, we may want to be able to pass a custom callback to `nextRoot` which would be passed down to `next-page-tester` for maximum flexibility. However, this would couple `next-page-tester` with `find-root`.

## Example

Considering the following folder hierarchy:

```
/
package.json
--/apps
----/my-next-js-app
----/next.config.js
```
`next-page-tester` automatically resolves `nextRoot` to `/apps/my-next-js-app`, rather than `/`.

**Comment by toomuchdesign** [comment]
Hi @jbmusso, I'd suggest to use `next-page-tester` through a wrapping function which enhances it with the necessary configuration. Just like `testing-library` suggests to do. In the mentioned case `find-root` could be a dev dependency used by the wrapping function. Would it work for your case?

**Comment by fbasilico** [comment]
@jbmusso Would you mind sharing your implementation of the wrapping function, I'm struggling with the same
