### ISSUE TITLE
Upgrading from jest v26 to v27 breaks working tests: ""

### ISSUE THREAD

**Issue by priti-wright** [toomuchdesign/next-page-tester#286]
## 🐛 Bug Report

Upgrading from jest v26 to v27 breaks working tests with Error: "TypeError: Cannot read property 'userAgent' of undefined"

## Reproduction
[Minimal  GitHub repo](https://github.com/priti-wright/next-page-tester-axios).

Run:
```bash
npm install;
npm test;
```

## Expected behavior

Tests should pass, with SSR api calls properly mocked out

## Jest patch

Have you patched Jest as [described here](https://github.com/toomuchdesign/next-page-tester#optional-patch-jest)?

- [ ] yes
- [ ] no
- [x] N/A

## Run `npx envinfo --preset jest`

```bash
  System:
    OS: macOS 12.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.7.0 - ~/.nvm/versions/node/v16.7.0/bin/node
    npm: 7.20.3 - ~/.nvm/versions/node/v16.7.0/bin/npm
  npmPackages:
    jest: ^27.3.1 => 27.3.1
```

**Comment by toomuchdesign** [comment]
Not related to `next-page-tester` itself. Probably related to `jest` configuration.

**Comment by priti-wright** [comment]
> Not related to `next-page-tester` itself. Probably related to `jest` configuration.

Can you expand a bit here? All that changed between the last two commits was the jest version.
