### ISSUE TITLE
Wrap page with document

### ISSUE THREAD

**Issue by Meemaw** [toomuchdesign/next-page-tester#29]
## 🚀 Feature Proposal

Wrap page with document (as it is currently done with App).

## Motivation

NextJS supports [custom `Document`](https://nextjs.org/docs/advanced-features/custom-document). There might be some involved logic there to render things (e.g. header meta attributes for SEO).

## Example

```ts
import { render, screen, fireEvent } from '@testing-library/react';
import { getPage } from 'next-page-tester';

describe('Blog page', () => {
  it('renders blog page', async () => {
    const { page } = await getPage({
      route: '/blog/1',
    });

    const { container } = render(page);
    expect(
      container.querySelector('meta[description="Description"]')
    ).toHaveAttribute('content', 'My custom description');
  });
});
```

**Comment by Meemaw** [comment]
I just realised this wain mentioned in todos already: https://github.com/toomuchdesign/next-page-tester#todos

Do you mind if I work on this @toomuchdesign ?

**Comment by toomuchdesign** [comment]
It'd be amazing, you're definitely welcome!
I have never ensured that basic Next Document component is actually renderable in JSDOM environment. Let's see. :)

Feel free to ping me for any question about the current codebase. ✌️
