### ISSUE TITLE
"No matching page found for given route"

### ISSUE THREAD

**Issue by kfazinic** [toomuchdesign/next-page-tester#31]
## 💬 Questions and Help
Hi! Trying to use this library in a Next + TS project. The error I get is below.
I used Vercel's [with-typescript-eslint-jest](https://github.com/vercel/next.js/tree/canary/examples/with-typescript-eslint-jest) example to create a **[minimal example that gives me the error](https://github.com/kfazinic/next-page-tester-with-ts-eslint)**.

Any idea why this might be? 
I'm on Windows 10, Node version 15.2.1. We use `next` 9.5.3 and `next-page-tester` 0.7.1.
```
$ yarn test
yarn run v1.22.0
$ jest
 FAIL  test/pages/index.test.tsx
  Home page
    × renders home page (28ms)

  ● Home page › renders home page

    [next page tester] No matching page found for given route

      15 | describe('Home page', () => {
      16 |   it('renders home page', async () => {
    > 17 |     const { page } = await getPage({
         |                      ^
      18 |       route: '/',
      19 |     })
      20 |

      at Object.getPageObject [as default] (node_modules/next-page-tester/dist/getPageObject.js:23:11)
      at Object.<anonymous> (test/pages/index.test.tsx:17:22)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Ran all test suites.
error Command failed with exit code 1.
```

**Comment by zkwsk** [comment]
I'm working on the same project and it might be worth noting that I'm running that test successfully on Mac OS 10.15 and Node 14.9.0.

**Comment by Meemaw** [comment]
I assume problem is usage of `/` for resolving paths. I can't test it on Windows, but I assume `path.join` and `path.sep` respectively should be used in places where paths are "concatenated"
