### ISSUE TITLE
Testing pages when persisting state with next-redux-wrapper

### ISSUE THREAD

**Issue by kfazinic** [toomuchdesign/next-page-tester#42]
## 💬 Questions and Help

Hi! Is there a way to use `next-page-tester` when blocking the UI from rendering while rehydrating the page? Using `next-redux-wrapper`'s `<PersistGate />` ([docs](https://github.com/kirill-konshin/next-redux-wrapper#usage-with-redux-persist)) to wrap page contents makes the tests fail because the full page hasn't yet been loaded when they execute.

Here's a [reproducible example](https://codesandbox.io/s/thirsty-dijkstra-x8gyh?file=/pages/_app.tsx). For proof of tests failing due to persisting state, they do pass if you uncomment line 25 in _app (but passing the `loading` prop to `<PersistGate />` is not a viable option in our project).

Any way to get around this in the tests?

```
import { useStore } from 'react-redux'
import { PersistGate } from 'redux-persist/integration/react'
import { wrapper } from '../redux/store'

const Root = ({ Component, pageProps }) => {
  const { __PERSISTOR } = useStore()

  return (
    <PersistGate
      persistor={__PERSISTOR}
    >
      <Component {...pageProps} />
    </PersistGate>
  )
}

export default wrapper.withRedux(Root)

```

**Comment by Meemaw** [comment]
I guess that is expected? But this seem to work (replaced `getByText` with `findByText`):

```ts
describe('Home page', () => {
  it('renders home page', async () => {
    const { page } = await getPage({
      route: '/'
    })

    render(page)
    await screen.findByText('Hi')
  })
})
```

**Comment by kfazinic** [comment]
@Meemaw thanks for the reply! :) 
This works
```
  describe("Home page", () => {
    it("renders home page", async () => {
      const { page } = await getPage({
        route: "/",
      });

      render(page);
      expect(await screen.findByText(/Hi/)).toBeInTheDocument();
    });
```
