### ISSUE TITLE
nextRoot tsconfig isn't picked up for import "@foo/bar" style resolution.

### ISSUE THREAD

**Issue by DavidOrchard** [toomuchdesign/next-page-tester#65]
## 🐛 Bug Report

Pages that have imports of style "@foo/bar", which are specified in tsconfig, aren't usable.

## To Reproduce

Page with import such as 
import "@foo/bar";

result in an error:
Cannot find module '@foo/bar' from '...';

## Expected behavior

Imports are correctly imported

## Run `npx envinfo --preset jest`

Paste the results here:

```bash
  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 12.16.0 - ~/.nvm/versions/node/v12.16.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.0/bin/npm
  npmPackages:
    jest: 26.6.1 => 26.6.1 

```

**Comment by toomuchdesign** [comment]
Custom module resolutions declared in `tsconfig` should be replicated in you test runner configuration. In case of Jest [`moduleNameMapper` option](https://jestjs.io/docs/en/configuration#modulenamemapper-objectstring-string--arraystring) should do the job.
