### ISSUE TITLE
Is it possible to fallback to default values for req, res mocks?

### ISSUE THREAD

**Issue by jasonwilliams** [toomuchdesign/next-page-tester#87]
## 🚀 Feature Proposal

I like the request and response mocks. However, a lot of my pages use the same data (headers, cookie values etc).
It would be nice to set this somewhere and then only override them when there's per-page differences.

## Motivation

Reduce repetition of mocking configuration for each page

## Example

Something as part of the initial setup

```js
import { initTestHelpers } from 'next-page-tester';
// Setup default values which can be called for all tests?
initTestHelpers({
  req: (req) => { },
  res: (res) => { }
});
```

Sidenote:
While im here i think the property and type are the wrong way around here:
https://github.com/toomuchdesign/next-page-tester#options

**Comment by Meemaw** [comment]
Hey @jasonwilliams 

I think it's possible to achieve what you want with wrapping `getPage` with your custom logic. Example:

```js
import { getPage } from 'next-page-tester'

const customGetPage = (options: ReturnType<typeof getPage>) => {
   return getPage({
      req: (req) => { },
      res: (res) => { },
      ...options
   }
}
```
